config/routes.rb
Personas::Application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'

  match "/oauth/authorize", :via => :get, :to => "authorization#new"
  match "/oauth/authorize", :via => :post, :to => "authorization#create"

  match "/profile" => "users#profile"
  match "/register" => "users#new"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :users
  resources :password_resets
  resources :sessions

  root :to => "users#new"
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    can :read, :all                   # allow everyone to read everything
    if user && user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard                  # allow access to dashboard
      can :manage, :all
    end
  end
end

app/models/oauth_access_token.rb
class OauthAccessToken < ActiveRecord::Base
end

app/models/oauth_authorization.rb
class OauthAuthorization < ActiveRecord::Base
end

app/models/oauth_authorization_code.rb
class OauthAuthorizationCode < ActiveRecord::Base
end

app/models/oauth_client.rb
class OauthClient < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :admin, as: :admin
  attr_accessible :email, :password_digest, :password, :password_confirmation, as: [ :default, :admin ]
  
  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_length_of :password, :minimum => 8
  validates_presence_of :password
  validates_presence_of :password_confirmation
  validates_confirmation_of :password

  before_save :email_downcase

  def email_downcase
    self.email = self.email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UrlHelper

  protect_from_forgery

  private

  def regrant_existing_authorization
    oauth2_authorization_request.grant_existing! current_user
  end

  def set_return_url
    session[:return_url] = request.request_uri
  end

  def return_url(params = {})
    if session[:return_url]
      if params.empty?
        session[:return_url]
      else
        session[:return_url] + "?" + params.to_param
      end
    else
      flash[:notice] = params[:message]
      root_url
    end
  end

  def authenticate_user
    unless current_user
      session[:return_url] = request.fullpath
      session[:client_id] = params[:client_id]

      respond_to do |format|
        format.html { redirect_to new_session_path }
        format.json { render json: { error: "access denied" } }
      end
    end
  end

  def set_current_user_from_oauth
    @current_user = request.env['oauth2'].resource_owner
  end

  def client
    @client ||= OAuth2::Provider::Models::Mongoid::Client.where({oauth_identifier: session[:client_id]}).first
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :client, :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  def scrape_client_page(page, message = nil)
    # Check if user is coming from another site
    ref = make_absolute(URI.encode(request.env['HTTP_REFERER']))
    host = make_absolute(request.url)
    if host != ref || session[:ref].present?
      # User is coming from client app
      if ref != host
        session[:ref] = ref
      else
        ref = session[:ref]
      end
      # Get the client app's page and alter it,
      # adding authenticity token and rewritting urls.
      if message
        url = "#{ref}#{page}?#{message.keys.first}=#{URI.escape(message.values.first)}"
      else
        url = "#{ref}#{page}"
      end
      doc = Nokogiri::HTML(open(url))
      if token = doc.at_css("input[name=authenticity_token]")
        token["value"] = form_authenticity_token
      end
      doc.css("a").map {|a|rewrite(a, 'href', ref)}
      doc.css("img").map {|img|rewrite(img, 'src', ref)}
      doc.css("link").map {|l|rewrite(l, 'href', ref)}
      doc.css("script").map {|s|rewrite(s, 'src', ref)}
      render :text => doc.to_s
    end
  end
end

app/controllers/authorization_controller.rb
class AuthorizationController < ApplicationController
  include OAuth2::Provider::Rack::AuthorizationCodesSupport

  before_filter :authenticate_user
  before_filter :block_invalid_authorization_code_requests
  before_filter :regrant_existing_authorization
  
  def new
    grant_authorization_code(current_user)
  end

  def create
    grant_authorization_code(current_user)
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
    scrape_client_page(new_password_reset_path)
  end

  def create
    user = User.where(email: params[:email]).first
    if user
      options = { query: { email: user.email } }
      url = session['ref'].to_s + "/password_resets"
      response = HTTParty.post(url, options)
      if response.body == "success"
        scrape_client_page new_password_reset_path,
        notice: "Email sent with password reset instructions."
      else
        scrape_client_page new_password_reset_path,
        notice: "Sorry, you haven't created an account for this site yet."
      end
    else
      scrape_client_page new_password_reset_path,
      error: "Sorry, no user was found with email address \"#{params[:email]}\"."
    end
  end

  def edit
    scrape_client_page(edit_password_reset_path)
    # if current_user
    #   @user = current_user
    # else
    #   redirect_to root_url
    # end
  end

  def update
    if current_user
      if current_user.update_attributes(params[:user])
        redirect_to root_url, :notice => "Password has been reset!"
      else
        @user = current_user
        render :edit
      end
    else
      redirect_to new_password_reset_url, :notice => "Please submit your email and follow the link to reset your password."
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    scrape_client_page("/login")
  end

  def create
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      session['ref'] = nil
      redirect_to return_url
    else
      scrape_client_page("/login", error: "Email or password is invalid.")
    end
  end

  def destroy
    # Remove user's session and return url
    session[:user_id] = session[:return_url] = nil
    if params[:redirect]
      redirect_to params[:redirect]
    else
      redirect_to root_url, :notice => "Logged out!"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authenticate_with_oauth :except => [:new, :create]
  before_filter :set_current_user_from_oauth, :except => [:new, :create]

  def new
    scrape_client_page("/signup")
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.json { render json: { uid: @user.id } }
        format.html { redirect_to session[:ref].to_s + "/auth/alphalogin", notice: "Thank you for signing up!" }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.html { scrape_client_page("/signup", error: @user.errors.full_messages.to_sentence) }
      end
    end
  end

  # GET /profile.json
  def profile
    if @current_user
      @user = @current_user
    else
      render json: {'error' => 'no user'}
    end
  end

  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      render json: {"success" => "true"}
    else
      render json: @user.errors["password"].first, status: :unprocessable_entity
    end
  end

  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    head :ok
  end

  # GET /users/find_by_role/:role
  def find_by_role
    if role = Role.where(name: params[:role]).first
      render json: role.accounts
    else
      render :json => {error:"not found"}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/url_helper.rb
module UrlHelper
  def make_absolute(uri)
    url = URI(uri)
    url.path = ''
    url.query = nil
    url
  end

  def rewrite(el, attr, base_url)
    if el[attr] =~ /^\//
      el[attr] = base_url.merge(el[attr]).to_s
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="user_header">
        <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<div class="main">
  <h2>Reset Password</h2>  
  <%= error_messages_for(@user) %>
	<% if flash[:error] %>
  <div class="alert alert-error">
	  <%=raw flash[:error] %>
  </div>
	<% flash[:error] = nil %>
	<% end %>
  <div class="visiting">
    <div class="block bootstrap">
      <%= form_for @user, :url => password_reset_path("password") do |f| %>
      <fieldset>
        <div class="control-group">
          <%= f.label :password %>
          <div class="controls">
            <%= f.password_field :password %>
          </div>
        </div>
      </fieldset>
      <fieldset>
        <div class="control-group">
          <label for="user_password_confirmation">Password <br />Confirmation</label>
          <div class="controls">
	          <%= f.password_field :password_confirmation %>
          </div>
        </div>
      </fieldset>
      <div class="actions">
        <button type="submit" class="btn btn-primary">
          <i class="icon-user icon-white"></i> Reset Password</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="sidebar">
  <div class="module">
    <h4>Reset Information</h4>
    <p>Please enter a new password and then enter the same password again to
    confirm it.</p>
  </div>
</div>

app/views/password_resets/new.html.erb
<div class="main">
  <h2>Reset Password</h2>  

	<% if flash[:error] %>
  <div class="alert alert-error">
	  <%=raw flash[:error] %>
  </div>
	<% flash[:error] = nil %>
	<% end %>
  <div class="visiting">
    <div class="block bootstrap">
      <%= form_tag password_resets_path do %>
      <fieldset>
        <div class="control-group">
          <%= label_tag :email %>
          <div class="controls">
            <%= text_field_tag :email, params[:email] %>
          </div>
        </div>
      </fieldset>
      <div class="actions">
        <button type="submit" class="btn btn-primary">
          <i class="icon-user icon-white"></i> Reset Password</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="sidebar">
  <div class="module">
    <h4>Reset Information</h4>
    <p>Please submit your email address and we'll send you
    instructions on how to reset your password.</p>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>